/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultor': typeof ConsultorRoute
  '/gestor': typeof GestorRoute
  '/operador': typeof OperadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultor': typeof ConsultorRoute
  '/gestor': typeof GestorRoute
  '/operador': typeof OperadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultor': typeof ConsultorRoute
  '/gestor': typeof GestorRoute
  '/operador': typeof OperadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/consultor' | '/gestor' | '/operador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/consultor' | '/gestor' | '/operador'
  id: '__root__' | '/' | '/admin' | '/consultor' | '/gestor' | '/operador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsultorRoute: typeof ConsultorRoute
  GestorRoute: typeof GestorRoute
  OperadorRoute: typeof OperadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsultorRoute: ConsultorRoute,
  GestorRoute: GestorRoute,
  OperadorRoute: OperadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
